[project]
name = "pyyaap"
version = "1.0.0"
authors = [
  { name="Dzianis Ivanchuk", email="twihkapb@gmail.com" },
]
description = "Python Yet Another Audio Package"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"